-- ============================================================================
-- SAST Shop v2 — 初始化数据库迁移
-- 服务: identity-member / catalog / group-trade / payment
-- 金额统一使用分为单位的整数，字段命名为 *_cents
-- 主键统一使用 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
-- 时间统一使用 TIMESTAMPTZ
-- 跨服务引用只保存业务语义 ID，不建立跨服务数据库外键
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Schemas
-- ----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "user";
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS spot;
CREATE SCHEMA IF NOT EXISTS errand;
CREATE SCHEMA IF NOT EXISTS payment;

-- ============================================================================
-- user schema — identity-member: 飞书身份、会话、用户资料、地址簿
-- ============================================================================
SET search_path TO "user";

-- 枚举 -----------------------------------------------------------------------

CREATE TYPE member_role AS ENUM ('user', 'admin');
COMMENT ON TYPE member_role IS '用户角色：user（普通用户）, admin（管理员）';

CREATE TYPE member_status AS ENUM ('active', 'restricted', 'banned', 'deleted');
COMMENT ON TYPE member_status IS '用户状态：active（正常）, restricted（受限）, banned（封禁）, deleted（已删除）';

CREATE TYPE auth_session_status AS ENUM ('active', 'revoked', 'expired');
COMMENT ON TYPE auth_session_status IS '会话状态：active（活跃）, revoked（主动撤销）, expired（过期）';

-- 表 -------------------------------------------------------------------------

-- 用户账户
CREATE TABLE user_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feishu_open_id  TEXT NOT NULL UNIQUE,
    role            member_role NOT NULL DEFAULT 'user',
    status          member_status NOT NULL DEFAULT 'active',
    display_name    TEXT NOT NULL,
    avatar_url      TEXT NOT NULL DEFAULT '',
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE user_account IS '用户账户表，通过飞书 OAuth 登录创建';
COMMENT ON COLUMN user_account.feishu_open_id IS '飞书 OpenID，唯一身份标识';
COMMENT ON COLUMN user_account.role IS '用户角色';
COMMENT ON COLUMN user_account.status IS '账户状态';
COMMENT ON COLUMN user_account.display_name IS '用户显示名称，从飞书账户获取';
COMMENT ON COLUMN user_account.avatar_url IS '用户头像 URL';
COMMENT ON COLUMN user_account.last_login_at IS '最近一次登录时间';

-- 认证会话（存储 refresh_token 哈希，现阶段不使用，仅为预设）
CREATE TABLE auth_session (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES user_account(id),
    refresh_token_hash  TEXT NOT NULL UNIQUE,
    status              auth_session_status NOT NULL DEFAULT 'active',
    expires_at          TIMESTAMPTZ NOT NULL,
    revoked_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE auth_session IS '认证会话表，只存储 refresh_token 的 SHA-256 哈希，明文 token 仅返回前端一次';
COMMENT ON COLUMN auth_session.refresh_token_hash IS 'refresh_token 的 SHA-256 哈希值';
COMMENT ON COLUMN auth_session.expires_at IS '会话过期时间';
COMMENT ON COLUMN auth_session.revoked_at IS '主动撤销时间';

-- 地址簿
CREATE TABLE member_address (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
    recipient_name   TEXT NOT NULL,
    recipient_phone  TEXT NOT NULL,
    province         TEXT NOT NULL DEFAULT '',
    city             TEXT NOT NULL DEFAULT '',
    district         TEXT NOT NULL DEFAULT '',
    detail_address   TEXT NOT NULL,
    is_default       BOOLEAN NOT NULL DEFAULT false,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE member_address IS '用户收货地址簿';

-- 每个用户最多一个默认地址
CREATE UNIQUE INDEX uq_member_default_address
ON member_address(user_id)
WHERE is_default = true;

-- ============================================================================
-- catalog schema — catalog: 店铺、商品模板、条码、商品图片
-- ============================================================================
SET search_path TO catalog;

-- 枚举 -----------------------------------------------------------------------

CREATE TYPE catalog_status AS ENUM ('draft', 'active', 'hidden', 'removed');
COMMENT ON TYPE catalog_status IS '目录状态：draft（草稿）, active（上架）, hidden（隐藏）, removed（已删除）';

-- 表 -------------------------------------------------------------------------

-- 店铺
CREATE TABLE catalog_store (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL,
    address           TEXT NOT NULL,
    logo_url          TEXT NOT NULL DEFAULT '',
    theme_color       TEXT NOT NULL DEFAULT '#FFFFFF',
    status            catalog_status NOT NULL DEFAULT 'active',
    created_by_user_id BIGINT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (name, address)
);
COMMENT ON TABLE catalog_store IS '店铺表';
COMMENT ON COLUMN catalog_store.created_by_user_id IS '创建者用户 ID（跨服务引用）';

-- 商品模板
CREATE TABLE catalog_product_template (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               TEXT NOT NULL,
    description         TEXT NOT NULL DEFAULT '',
    price_cents         INTEGER NOT NULL CHECK (price_cents >= 0),
    store_id            BIGINT NOT NULL REFERENCES catalog_store(id),
    status              catalog_status NOT NULL DEFAULT 'active',
    created_by_user_id  BIGINT NOT NULL,
    published_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE catalog_product_template IS '商品模板表，定义商品展示信息，不表达库存';
COMMENT ON COLUMN catalog_product_template.price_cents IS '商品价格（单位：分）';
COMMENT ON COLUMN catalog_product_template.created_by_user_id IS '创建者用户 ID（跨服务引用）';

-- 商品条码
CREATE TABLE catalog_product_barcode (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_template_id  BIGINT NOT NULL REFERENCES catalog_product_template(id) ON DELETE CASCADE,
    barcode              TEXT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (barcode, product_template_id)
);
COMMENT ON TABLE catalog_product_barcode IS '商品条码表，一个商品模板可关联多个条码';

-- 商品图片
CREATE TABLE catalog_product_image (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_template_id  BIGINT NOT NULL REFERENCES catalog_product_template(id) ON DELETE CASCADE,
    image_url            TEXT NOT NULL,
    sort_order           INTEGER NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE catalog_product_image IS '商品图片表，按 sort_order 排序展示';

-- ============================================================================
-- spot schema — group-trade 现货团购
-- ============================================================================
SET search_path TO spot;

-- 枚举 -----------------------------------------------------------------------

CREATE TYPE spot_order_status AS ENUM ('pending_payment', 'paid', 'completed', 'cancelled');
COMMENT ON TYPE spot_order_status IS '现货订单状态：pending_payment（待支付）, paid（已支付）, completed（已完成）, cancelled（已取消）';

CREATE TYPE stock_ledger_reason AS ENUM ('publish', 'order_lock', 'order_cancel', 'manual_adjust');
COMMENT ON TYPE stock_ledger_reason IS '库存变动原因：publish（上架）, order_lock（下单锁库存）, order_cancel（取消订单释放）, manual_adjust（手动调整）';

-- 表 -------------------------------------------------------------------------

-- 现货商品（上架 listing）
CREATE TABLE spot_goods (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id            BIGINT NOT NULL,
    store_id             BIGINT NOT NULL,
    product_template_id  BIGINT NOT NULL,
    sale_price_cents     INTEGER NOT NULL CHECK (sale_price_cents >= 0),
    stock_total          INTEGER NOT NULL CHECK (stock_total >= 0),
    closed_at            TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE spot_goods IS '现货商品表，卖家上架的现货 listing';
COMMENT ON COLUMN spot_goods.seller_id IS '卖家用户 ID（跨服务引用）';
COMMENT ON COLUMN spot_goods.store_id IS '店铺 ID（跨服务引用）';
COMMENT ON COLUMN spot_goods.product_template_id IS '商品模板 ID（跨服务引用 catalog.catalog_product_template）';
COMMENT ON COLUMN spot_goods.sale_price_cents IS '售价（单位：分）';
COMMENT ON COLUMN spot_goods.stock_total IS '当前库存总量';

-- 库存流水
CREATE TABLE spot_stock_ledger (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  BIGINT NOT NULL REFERENCES spot_goods(id),
    delta       INTEGER NOT NULL,
    reason      stock_ledger_reason NOT NULL DEFAULT 'publish',
    ref_type    TEXT NOT NULL DEFAULT '',
    ref_id      BIGINT,
    operator_id BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE spot_stock_ledger IS '库存流水表，记录所有库存变动';
COMMENT ON COLUMN spot_stock_ledger.delta IS '库存变化量，正数为增加，负数为减少';
COMMENT ON COLUMN spot_stock_ledger.ref_type IS '关联业务类型（如 spot_order）';
COMMENT ON COLUMN spot_stock_ledger.ref_id IS '关联业务 ID';
COMMENT ON COLUMN spot_stock_ledger.operator_id IS '操作人用户 ID（跨服务引用）';

-- 现货订单
CREATE TABLE spot_order (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no              TEXT NOT NULL UNIQUE,
    purchaser_id          BIGINT NOT NULL,
    listing_id            BIGINT NOT NULL REFERENCES spot_goods(id),
    product_template_id   BIGINT NOT NULL,
    title_snapshot        TEXT NOT NULL,
    description_snapshot  TEXT NOT NULL DEFAULT '',
    image_url_snapshot    TEXT NOT NULL DEFAULT '',
    quantity              INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_cents      INTEGER NOT NULL CHECK (unit_price_cents >= 0),
    total_amount_cents    INTEGER NOT NULL CHECK (total_amount_cents >= 0),
    payment_bill_id       BIGINT,
    status                spot_order_status NOT NULL DEFAULT 'pending_payment',
    paid_at               TIMESTAMPTZ,
    completed_at          TIMESTAMPTZ,
    cancelled_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE spot_order IS '现货订单表';
COMMENT ON COLUMN spot_order.order_no IS '对外订单编号，唯一';
COMMENT ON COLUMN spot_order.purchaser_id IS '买家用户 ID（跨服务引用）';
COMMENT ON COLUMN spot_order.product_template_id IS '商品模板 ID（跨服务引用）';
COMMENT ON COLUMN spot_order.title_snapshot IS '下单时商品标题快照';
COMMENT ON COLUMN spot_order.description_snapshot IS '下单时商品描述快照';
COMMENT ON COLUMN spot_order.image_url_snapshot IS '下单时商品主图 URL 快照';
COMMENT ON COLUMN spot_order.unit_price_cents IS '下单时单价（单位：分）';
COMMENT ON COLUMN spot_order.total_amount_cents IS '订单总金额（单位：分）= unit_price_cents × quantity';
COMMENT ON COLUMN spot_order.payment_bill_id IS '关联支付账单 ID（跨服务引用 payment.payment_bill）';

-- ============================================================================
-- errand schema — group-trade 跑腿采购
-- 详细业务流程见 PRD §5.1 跑腿采购全流程
-- ============================================================================
SET search_path TO errand;

-- 枚举 -----------------------------------------------------------------------

CREATE TYPE errand_demand_status AS ENUM (
    'open',
    'shopping',
    'pending_distributing',
    'distributing',
    'pending_payment',
    'completed',
    'cancelled'
);
COMMENT ON TYPE errand_demand_status IS '跑腿需求状态（买家视角）';

CREATE TYPE errand_demand_item_status AS ENUM (
    'open',
    'shopping',
    'pending_distributing',
    'distributing',
    'pending_payment',
    'completed',
    'cancelled'
);
COMMENT ON TYPE errand_demand_item_status IS '跑腿需求行状态';

CREATE TYPE errand_task_status AS ENUM (
    'shopping',
    'pending_distributing',
    'distributing',
    'collecting_payment',
    'completed',
    'cancelled'
);
COMMENT ON TYPE errand_task_status IS '跑腿任务状态（团长视角）';

-- 表 -------------------------------------------------------------------------

-- 跑腿需求（买家视角的跑腿订单）
CREATE TABLE errand_demand (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id          BIGINT NOT NULL,
    store_id              BIGINT NOT NULL,
    status                errand_demand_status NOT NULL DEFAULT 'open',
    deadline              TIMESTAMPTZ NOT NULL CHECK (deadline > now()),
    task_id               BIGINT,
    split_from_demand_id  BIGINT REFERENCES errand_demand(id),
    shopping_start_at     TIMESTAMPTZ,
    shopping_completed_at TIMESTAMPTZ,
    distribution_completed_at TIMESTAMPTZ,
    payment_completed_at  TIMESTAMPTZ,
    cancelled_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE errand_demand IS '跑腿需求表，买家视角的跑腿订单';
COMMENT ON COLUMN errand_demand.requester_id IS '需求发起人用户 ID（跨服务引用）';
COMMENT ON COLUMN errand_demand.store_id IS '目标店铺 ID（跨服务引用）';
COMMENT ON COLUMN errand_demand.task_id IS '关联的团长任务 ID';
COMMENT ON COLUMN errand_demand.split_from_demand_id IS '拆分来源 demand ID，用于追溯部分接单的原始订单';

-- 跑腿需求行
CREATE TABLE errand_demand_item (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    errand_demand_id             BIGINT NOT NULL REFERENCES errand_demand(id) ON DELETE CASCADE,
    requester_id                 BIGINT NOT NULL,
    store_id                     BIGINT NOT NULL,
    product_template_id          BIGINT NOT NULL,
    estimated_unit_price_cents   INTEGER NOT NULL CHECK (estimated_unit_price_cents >= 0),
    quantity                     INTEGER NOT NULL CHECK (quantity > 0),
    service_fee_per_unit_cents   INTEGER NOT NULL CHECK (service_fee_per_unit_cents >= 0),
    status                       errand_demand_item_status NOT NULL DEFAULT 'open',
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (errand_demand_id, product_template_id)
);
COMMENT ON TABLE errand_demand_item IS '跑腿需求行表，买家订单中的单个商品需求';
COMMENT ON COLUMN errand_demand_item.product_template_id IS '商品模板 ID（跨服务引用 catalog.catalog_product_template）';
COMMENT ON COLUMN errand_demand_item.estimated_unit_price_cents IS '预估单价（单位：分）';
COMMENT ON COLUMN errand_demand_item.service_fee_per_unit_cents IS '单个商品跑腿费（单位：分）';
COMMENT ON COLUMN errand_demand_item.quantity IS '需求数量';

-- 跑腿任务（团长视角的采购任务）
CREATE TABLE errand_task (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no                  TEXT NOT NULL UNIQUE,
    captain_id               BIGINT NOT NULL,
    store_id                 BIGINT NOT NULL,
    status                   errand_task_status NOT NULL DEFAULT 'shopping',
    packaging_fee_cents      INTEGER NOT NULL DEFAULT 0 CHECK (packaging_fee_cents >= 0),
    shopping_completed_at    TIMESTAMPTZ,
    distribution_completed_at TIMESTAMPTZ,
    payment_completed_at     TIMESTAMPTZ,
    cancelled_at             TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE errand_task IS '跑腿任务表，团长视角的采购任务';
COMMENT ON COLUMN errand_task.captain_id IS '团长用户 ID（跨服务引用）';
COMMENT ON COLUMN errand_task.store_id IS '目标店铺 ID（跨服务引用）';
COMMENT ON COLUMN errand_task.packaging_fee_cents IS '包装费分摊总额（单位：分）';

-- 跑腿任务采购清单
CREATE TABLE errand_task_item (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id               BIGINT NOT NULL REFERENCES errand_task(id) ON DELETE CASCADE,
    product_template_id   BIGINT NOT NULL,
    title_snapshot        TEXT NOT NULL,
    description_snapshot  TEXT NOT NULL DEFAULT '',
    image_url_snapshot    TEXT NOT NULL DEFAULT '',
    required_quantity     INTEGER NOT NULL CHECK (required_quantity > 0),
    purchased_quantity    INTEGER CHECK (purchased_quantity IS NULL OR purchased_quantity >= 0),
    non_purchase_reason   TEXT NOT NULL DEFAULT '',
    actual_unit_price_cents INTEGER CHECK (actual_unit_price_cents >= 0),
    deadline              TIMESTAMPTZ NOT NULL,
    handled_at            TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (task_id, product_template_id, deadline)
);
COMMENT ON TABLE errand_task_item IS '跑腿任务采购清单，按 product_template_id + deadline 聚合需求行';
COMMENT ON COLUMN errand_task_item.title_snapshot IS '采购时从 catalog 固化的商品标题快照';
COMMENT ON COLUMN errand_task_item.required_quantity IS '需求总数量';
COMMENT ON COLUMN errand_task_item.purchased_quantity IS '实际采购数量，NULL 表示尚未处理';
COMMENT ON COLUMN errand_task_item.actual_unit_price_cents IS '实际采购单价（单位：分），团长改价后更新';

-- 任务分配（task_item 与 demand_item 的关联）
CREATE TABLE errand_task_assignment (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id                   BIGINT NOT NULL REFERENCES errand_task(id) ON DELETE CASCADE,
    task_item_id              BIGINT NOT NULL REFERENCES errand_task_item(id) ON DELETE CASCADE,
    demand_item_id            BIGINT NOT NULL UNIQUE REFERENCES errand_demand_item(id),
    purchaser_id              BIGINT NOT NULL,
    distributed_quantity      INTEGER NOT NULL DEFAULT 0 CHECK (distributed_quantity >= 0),
    service_fee_per_unit_cents INTEGER NOT NULL CHECK (service_fee_per_unit_cents >= 0),
    payment_bill_id           BIGINT,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE errand_task_assignment IS '任务分配表，关联 task_item 与 demand_item，一个 demand_item 只能被接单一次';
COMMENT ON COLUMN errand_task_assignment.demand_item_id IS '唯一约束，确保一个需求行不会被重复接单';
COMMENT ON COLUMN errand_task_assignment.purchaser_id IS '购买人用户 ID（跨服务引用）';
COMMENT ON COLUMN errand_task_assignment.distributed_quantity IS '实际分发数量';
COMMENT ON COLUMN errand_task_assignment.payment_bill_id IS '关联支付账单 ID（跨服务引用 payment.payment_bill）';

-- 改价日志
CREATE TABLE errand_price_change_log (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_item_id         BIGINT NOT NULL REFERENCES errand_task_item(id) ON DELETE CASCADE,
    operator_id          BIGINT NOT NULL,
    old_unit_price_cents INTEGER,
    new_unit_price_cents INTEGER NOT NULL CHECK (new_unit_price_cents >= 0),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE errand_price_change_log IS '跑腿改价日志，记录每次单价变更';
COMMENT ON COLUMN errand_price_change_log.old_unit_price_cents IS '旧单价（单位：分），首次改价时为 NULL';

-- 操作审计日志
CREATE TABLE errand_action_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      BIGINT NOT NULL REFERENCES errand_task(id) ON DELETE CASCADE,
    actor_id     BIGINT NOT NULL,
    target_type  TEXT NOT NULL,
    target_id    BIGINT NOT NULL,
    action       TEXT NOT NULL,
    before_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_state  JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE errand_action_log IS '跑腿操作审计日志，记录状态变更前后快照';

-- ============================================================================
-- payment schema — payment: 收款码、支付账单、付款提交、确认收款
-- ============================================================================
SET search_path TO payment;

-- 枚举 -----------------------------------------------------------------------

CREATE TYPE payment_channel AS ENUM ('wechat', 'alipay');
COMMENT ON TYPE payment_channel IS '支付渠道：wechat（微信）, alipay（支付宝）';

CREATE TYPE payment_bill_status AS ENUM ('unpaid', 'submitted', 'completed', 'closed');
COMMENT ON TYPE payment_bill_status IS '支付账单状态：unpaid（待支付）, submitted（已提交/待确认）, completed（已完成）, closed（已关闭）';

-- 表 -------------------------------------------------------------------------

-- 收款二维码
CREATE TABLE payment_qr_code (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT NOT NULL,
    channel    payment_channel NOT NULL,
    content    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE payment_qr_code IS '收款二维码表，保存二维码解析后的 content，不保存图片文件';
COMMENT ON COLUMN payment_qr_code.owner_id IS '收款码所有者用户 ID（跨服务引用）';
COMMENT ON COLUMN payment_qr_code.content IS '二维码解析后的文本内容';

-- 每个用户每个渠道最多一个默认收款码
CREATE UNIQUE INDEX uq_payment_qr_owner_channel
ON payment_qr_code(owner_id, channel);

-- 支付账单
CREATE TABLE payment_bill (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_no         TEXT NOT NULL UNIQUE,
    payer_id        BIGINT NOT NULL,
    payee_id        BIGINT NOT NULL,
    source_type     TEXT,
    source_id       BIGINT,
    amount_cents    INTEGER NOT NULL CHECK (amount_cents >= 0),
    verify_code     TEXT NOT NULL CHECK (verify_code ~ '^[0-9]{4}$'),
    status          payment_bill_status NOT NULL DEFAULT 'unpaid',
    channel         payment_channel,
    serial_number   TEXT NOT NULL DEFAULT '',
    submitted_at    TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    closed_at       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE payment_bill IS '支付账单表';
COMMENT ON COLUMN payment_bill.bill_no IS '对外账单编号，唯一';
COMMENT ON COLUMN payment_bill.payer_id IS '付款方用户 ID（跨服务引用）';
COMMENT ON COLUMN payment_bill.payee_id IS '收款方用户 ID（跨服务引用）';
COMMENT ON COLUMN payment_bill.source_type IS '业务来源类型：spot_order / errand_task';
COMMENT ON COLUMN payment_bill.source_id IS '业务来源 ID';
COMMENT ON COLUMN payment_bill.amount_cents IS '支付金额（单位：分）';
COMMENT ON COLUMN payment_bill.verify_code IS '4 位随机数字核验码';
COMMENT ON COLUMN payment_bill.serial_number IS '忘记填校验码时的补充信息';

-- 幂等约束：同一来源 + 同一付款人仅允许存在一张账单
-- 详见 PRD §5.3 支付账单幂等
CREATE UNIQUE INDEX uq_payment_bill_source
ON payment_bill(source_type, source_id, payer_id)
WHERE source_type IS NOT NULL AND source_id IS NOT NULL;

-- 支付确认日志
CREATE TABLE payment_confirmation_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id      BIGINT NOT NULL REFERENCES payment_bill(id) ON DELETE CASCADE,
    operator_id  BIGINT NOT NULL,
    from_status  payment_bill_status NOT NULL,
    to_status    payment_bill_status NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE payment_confirmation_log IS '支付确认日志，记录账单状态变更';
COMMENT ON COLUMN payment_confirmation_log.operator_id IS '操作人用户 ID（跨服务引用）';
